version: "3.9"

services:
  notification-server-go:
    container_name: notification-server-go
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3020:3020"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - notification_net

networks:
  notification_net:
    external: true
    name: notification_net
